name: Deploy to Nginx Default Path

on:
  push:
    branches:
      - main  # or whichever branch you want

jobs:
  deploy:
    name: Pull and Deploy Code
    runs-on: self-hosted  # This will run on your GCP VM with Nginx

    steps:
      - name: Checkout Code from GitHub
        uses: actions/checkout@v3

      - name: Copy code to Nginx default directory
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/
