name: Deploy Website to Nginx

on:
  push:
    branches:
      - main  # adjust if using a different branch

jobs:
  deploy:
    name: Deploy via Self-Hosted Runner
    runs-on: self-hosted  # uses your GCP runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean old site files
        run: |
          sudo rm -rf /var/www/html/*

      - name: Copy new files to Nginx root
        run: |
          sudo cp -r . /var/www/html/

      - name: (Optional) Restart Nginx
        run: |
          sudo systemctl restart nginx
