name: Test Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print hostname
        run: hostname
      - name: install git
        run: sudo apt install git -y

      - name: Deploy the code
        run: |
          cd /var/www
          if [ ! -d "html/.git" ]; then
            sudo rm -rf html
            git clone https://github.com/mdmojahid20/test7.git html
          else
            cd html
            git pull origin main
          fi

