runs-on: self-hosted

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Deploy the code
    run: |
      cd /var/www/html
      git pull origin main
      # optional: restart nginx, pm2, etc.
