name: Test Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GCP via Self-Hosted Runner
    runs-on: self-hosted  # Make sure your runner is registered as self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GCP VM
        run: |
          ssh ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }} << 'EOF'
            cd /var/www/html
            git pull origin main
            # Optional: Restart services
            # sudo systemctl restart nginx
            # docker-compose down && docker-compose up -d
          EOF
